[package]
name = "snake_gpu_rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "snake_gpu_rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
wgpu = "22"
pollster = "0.3"

bytemuck = { version = "1.16", features = ["derive"] }
